version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./vol/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - opensoc

  thehive:
    image: strangebee/thehive:5.1
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - ./vol/thehive:/etc/thehive
    networks:
      - opensoc
    depends_on:
      - elasticsearch

  cortex:
    image: thehiveproject/cortex:3.1
    environment:
      - JOB_DIRECTORY=/tmp/cortex-jobs
    volumes:
      - ./vol/cortex:/etc/cortex
    networks:
      - opensoc
    depends_on:
      - elasticsearch

  traefik:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=user@example.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/letsencrypt
    networks:
      - opensoc

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - N8N_HOST=n8n.example.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - ./vol/n8n:/home/node/.n8n
      - ./vol/local-files:/files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.example.com`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
    networks:
      - opensoc
    restart: always

volumes:
  traefik_data:

networks:
  opensoc:
    driver: bridge
