version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./vol/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - opensoc

  thehive:
    image: strangebee/thehive:5.1
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "9000:9000"
    volumes:
      - ./vol/thehive:/etc/thehive
    networks:
      - opensoc
    depends_on:
      - elasticsearch

  cortex:
    image: thehiveproject/cortex:3.1
    environment:
      - JOB_DIRECTORY=/tmp/cortex-jobs
    ports:
      - "9001:9001"
    volumes:
      - ./vol/cortex:/etc/cortex
    networks:
      - opensoc
    depends_on:
      - elasticsearch

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - ./vol/n8n:/home/node/.n8n
      - ./vol/local-files:/files
    networks:
      - opensoc
    restart: always

networks:
  opensoc:
    driver: bridge
