version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./vol/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - opensoc

  thehive:
    image: strangebee/thehive:5.1
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "9000:9000"
    volumes:
      - ./vol/thehive:/etc/thehive
    networks:
      - opensoc
    depends_on:
      - elasticsearch

  cortex:
    image: thehiveproject/cortex:3.1
    environment:
      - JOB_DIRECTORY=/tmp/cortex-jobs
    ports:
      - "9001:9001"
    volumes:
      - ./vol/cortex:/etc/cortex
    networks:
      - opensoc
    depends_on:
      - elasticsearch

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./vol/n8n:/home/node/.n8n
      - ./vol/local-files:/files
    networks:
      - opensoc
    restart: always

  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.3
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    volumes:
      - ./vol/wazuh/config:/wazuh-config
      - ./vol/wazuh/data:/var/ossec/data
    networks:
      - opensoc

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.3
    hostname: wazuh.dashboard
    restart: always
    ports:
      - "5601:5601"
    environment:
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=admin
    networks:
      - opensoc

networks:
  opensoc:
    driver: bridge
